version: '3.8'

services:
  app:
    build: .
    ports:
      - "0.0.0.0:3000:3000"  # Bind to all network interfaces
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
